name cad_gpt
channels
  - cadquery
  - conda-forge
  - nvidia
dependencies
  - python=3.11
  - pip
  - libgl-mesa
  - mesa-libgl
  - libglib
  - libx11
  - libxext
  - libxrender
  - libfontconfig
  - libsm
  - pip
    - streamlit==1.55.0
    - groq==1.1.1
    - cadquery==2.2.0
    - numpy2.0.0